default_stages: [ commit, push ]
fail_fast: true

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.10
    hooks:
      - id: ruff
        name: Ruff (fix)
        args: [ --fix, --verbose ]
        stages: [ commit ]
        types: [ python ]
        language_version: python3.12
        additional_dependencies: [ ruff==0.11.10 ]

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        name: Black (formatting)
        language_version: python3.12
        stages: [ commit ]
        types: [ python ]
        args: [ --safe, --quiet ]

  - repo: local
    hooks:
      - id: mypy
        name: Mypy (type checking)
        entry: poetry run mypy --install-types --non-interactive --strict src/ tests/
        language: system
        pass_filenames: false
        stages: [ push ]
        always_run: true

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
        args: [ --maxkb=500 ]
      - id: check-ast
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
        stages: [ commit ]

